#ifndef _VERSION_H
#define _VERSION_H

#define KERNEL_VERSION_MAJOR 0
#define KERNEL_VERSION_MINOR 1
#define KERNEL_VERSION_PATCH 0
#define KERNEL_VERSION_ABI 1

#define KERNEL_VERSION_STR "0.1.0"
#define KERNEL_VERSION_GIT "2864b8f-dirty"
#define KERNEL_BUILD_DATE_UTC "2026-02-25T06:27:38Z"
#define KERNEL_VERSION_FULL "0.1.0-g2864b8f-dirty"

#endif
